Change Theme Button visible now in md screen
girlscript/gssoc-website-new pull request #103
Opened 2023-05-15 13:28 UTC by mohdhaider07

All the changes made is navbar.js
and theme change button is removed from index.js file(home screen)

2023-05-16 19:38 UTC, Suvraneel requested changes

2023-05-16 19:38 UTC, Suvraneel commented on components/Navbar.js
> +					<a className="inline-flex items-center p-2 mr-4 ">
@mohdhaider07 
Please do not change lines that have not been changed.
This repository uses an indentation of 2 spaces in contrast to your formatter which uses 4 spaces.

2023-05-17 20:32 UTC, mohdhaider07 commented on components/Navbar.js
> +					<a className="inline-flex items-center p-2 mr-4 ">
Okay

2023-05-19 07:47 UTC, Suvraneel commented
@mohdhaider07  No difference bro.

Basically these lines shouldn't appear in diff:
![image](https://github.com/girlscript/gssoc-website-new/assets/63473496/621225c7-b6b9-418e-97af-68a9ecbc904f)

Make a new PR if you need

2023-05-19 14:52 UTC, mohdhaider07 commented
>
I've made changes specifically in Navbar.js and Index.js, and I don't believe it's a significant issue. You can go ahead and merge them."

2023-05-19 22:28 UTC, Suvraneel commented
@mohdhaider07  
I totally understand and agree with you. Indentation sizes don't matter.🖤

But in large codebases it's always advisable to preserve git history because it's easier to `git blame` someone incase something goes wrong. 

Moreover, modifying irrelevant lines also gives a false weightage to the extent of the PR (if I assign a level 1 to this PR, someone might disagree if he feels it was unjustified).

( I've no issues merging this, but we're supposed to be preaching good open-source practices. Hence, here we go )

2023-05-20 04:25 UTC, mohdhaider07 commented
@Suvraneel thanks for explaining got your point

2023-05-20 04:56 UTC, closed without merging