Added Sponsor Us Page (Both Frontend and Backend) along with Nodemailer
girlscript/gssoc-website-new pull request #375
Opened 2024-09-08 23:16 UTC by shreyash3087

**Description:**

This PR adds the whole Frontend as well as Backend for the Sponsor Us Page.
It also integrates the sponsor us page with nodemailer that sends automatic mails to "Organisation Email" of the sponsor. 

**Video:**

https://github.com/user-attachments/assets/b16696f4-80f4-40f7-b2d2-4dada92b7a52

**Additional Context:**

- The Mail is Temporary, if someone has any other design in mind for the mail they can share it out over here.
- Kindly share your thoughts on what should i put in the placeholders for previous sponsors,just a logo of postman,xyz or something else

2024-09-08 23:21 UTC, MastanSayyad approved these changes

2024-09-08 23:21 UTC, vansh-codes approved these changes

2024-09-09 00:48 UTC, sanjay-kv approved these changes

2024-09-09 03:26 UTC, Hemu21 requested changes
For now you can add the postman , .xyz, vercel, etc from the main of gssoc.

2024-09-09 03:44 UTC, RadhikaMalpani1702 approved these changes

2024-09-09 03:56 UTC, Meetjain1 approved these changes

2024-09-09 04:15 UTC, aditya-bhaumik approved these changes

2024-09-09 04:19 UTC, suhanipaliwal approved these changes

2024-09-09 04:55 UTC, UppuluriKalyani approved these changes

2024-09-09 05:43 UTC, shreyash3087 commented
![screencapture-localhost-3000-sponsor-us-2024-09-09-11_13_03](https://github.com/user-attachments/assets/f3d30be7-7811-449f-bcaf-2f8c5073f486)

2024-09-09 05:44 UTC, shreyash3087 commented
@Hemu21 is it okay?

2024-09-09 06:05 UTC, sanjay-kv commented
Man thats so good. 

@Hemu21 

Should we have a page to download the sponsorship deck or some details saying whats next for you 

which says we will get back in 5 days and poc email id is here or should attach sponsorship doc
https://github.com/GSSoC24/being-an-GSSoc24/wiki/Sponsership-Tracking

2024-09-09 11:22 UTC, shreyash3087 commented
@sanjay-kv something like this? 

![screencapture-localhost-3000-sponsor-us-2024-09-09-16_45_32 (1)](https://github.com/user-attachments/assets/0c5fd517-5726-4c88-987d-a60a48b3f4c2)

2024-09-09 11:37 UTC, MastanSayyad approved these changes

2024-09-09 12:52 UTC, Hemu21 approved these changes

2024-09-09 12:53 UTC, merged