New Popup to notify visitors about GSSoC'24 Extd
girlscript/gssoc-website-new pull request #386
Opened 2024-09-12 14:48 UTC by vansh-codes

Closes: https://github.com/GSSoC24/being-an-GSSoc24/issues/194

Old Popup:
![image](https://github.com/user-attachments/assets/c229f666-ec60-40bf-9882-7bb8a858765e)

New Popup:
![image](https://github.com/user-attachments/assets/53865334-ff61-49fc-ac80-a2a4475c6ee9)

It will update dynamically as per the date and time to update the data and timer on popup

Updated timer time to ellapse at 5.30PM as said by Mastan ✅

2024-09-12 14:50 UTC, Hemu21 approved these changes

2024-09-12 15:07 UTC, RadhikaMalpani1702 approved these changes

2024-09-12 15:35 UTC, suhanipaliwal approved these changes

2024-09-12 15:43 UTC, MastanSayyad requested changes
add two buttons, register here (with registratin link) and learn more with home page

2024-09-12 19:48 UTC, MastanSayyad approved these changes

2024-09-13 02:42 UTC, Meetjain1 approved these changes

2024-09-13 05:21 UTC, Hemu21 approved these changes

2024-09-13 05:21 UTC, merged

2024-09-13 05:24 UTC, RadhikaMalpani1702 approved these changes