New Badge download page for registrars
girlscript/gssoc-website-new pull request #402
Opened 2024-09-14 14:13 UTC by vansh-codes

Closes: 

- Added new page `/badgeID` for users to download their badge according to their roles and showcase on social media and linkedin

https://github.com/user-attachments/assets/25cb702e-d839-41ea-a17e-1bb349c164fc

2024-09-14 14:16 UTC, MastanSayyad approved these changes

2024-09-14 14:18 UTC, RadhikaMalpani1702 approved these changes

2024-09-14 14:43 UTC, suhanipaliwal approved these changes

2024-09-14 14:53 UTC, Hemu21 approved these changes

2024-09-14 15:08 UTC, aditya-bhaumik approved these changes

2024-09-14 15:09 UTC, aslams2020 approved these changes

2024-09-14 15:34 UTC, shreyash3087 approved these changes

2024-09-14 18:34 UTC, MastanSayyad approved these changes

2024-09-14 18:55 UTC, MastanSayyad requested changes
One minor change date should be from 1st Oct 2024 to 30th Oct 2024! @vansh-codes

2024-09-14 19:01 UTC, vansh-codes commented
On it!

2024-09-14 19:12 UTC, MastanSayyad approved these changes
One Minor Change

The date should be from 1st Oct t

2024-09-15 04:28 UTC, suhanipaliwal approved these changes

2024-09-15 07:49 UTC, merged