Feat: Completes Frontend for CA Leaderboards
girlscript/gssoc-website-new pull request #404
Opened 2024-09-14 15:15 UTC by shreyash3087

**Description:**

This PR completes the frontend of CA Leaderboards,and enures every feature works fine

**Image:**

![screencapture-localhost-3000-caLeaderboard-2024-09-14-19_57_56](https://github.com/user-attachments/assets/f860a969-8d0b-4569-aa76-0692472a2166)

**Additional Context:**

N/A

2024-09-14 15:24 UTC, shreyash3087 commented
@sanjay-kv @hemu @MastanSayyad 

This is the Backend Server - https://github.com/girlscript/gssoc24-leaderboard-backend/pull/4

@Hemu21 checkout the server.js file once and see if everything is okay

2024-09-14 15:25 UTC, shreyash3087 commented
@Hemu21 also need to change the endpoint after the deployment currently its localhost:3000/CALeaderboards, update me with the server url and ill edit it in the frontend

2024-09-14 17:21 UTC, Hemu21 approved these changes

2024-09-14 17:23 UTC, MastanSayyad approved these changes

2024-09-14 17:25 UTC, suhanipaliwal approved these changes

2024-09-14 17:29 UTC, Hemu21 requested changes
In more options add the CA Leaderboard  navigating.

2024-09-14 22:12 UTC, MastanSayyad approved these changes

2024-09-15 03:35 UTC, RadhikaMalpani1702 approved these changes

2024-09-15 08:02 UTC, Hemu21 approved these changes

2024-09-15 08:08 UTC, sanjay-kv approved these changes

2024-09-15 11:38 UTC, merged